spring:
  r2dbc:
    url: r2dbc:mysql://${CONF_MODU_TICKET_DB_HOST:localhost}:${CONF_MODU_TICKET_DB_PORT:3306}/${CONF_MODU_TICKET_DB_DATABASE:modu_ticket}
    username: ${CONF_MODU_TICKET_DB_USERNAME:root}
    password: ${CONF_MODU_TICKET_DB_PASSWORD:local}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:mysql://${CONF_MODU_TICKET_DB_HOST:localhost}:${CONF_MODU_TICKET_DB_PORT:3306}/${CONF_MODU_TICKET_DB_DATABASE:modu_ticket}
    user: ${CONF_MODU_TICKET_DB_USERNAME:root}
    password: ${CONF_MODU_TICKET_DB_PASSWORD:local}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /api/**
jwt:
  header: Authorization
  secret: bW9kdS10aWNrZXQ=
  token-validity-in-seconds: 60
portone:
  baseurl: https://api.iamport.kr/
  api-key: 9502472691574730
  api-secret: f9f95d77d9a67a903a9103f7be727a23394a4bab6612efbb2ad7de08162d1fb3879ac6f84acca91f