spring:
  r2dbc:
    url: r2dbc:mysql://${CONF_MODU_TICKET_DB_HOST:localhost}:${CONF_MODU_TICKET_DB_PORT:3306}/${CONF_MODU_TICKET_DB_DATABASE:modu_ticket}
    username: ${CONF_MODU_TICKET_DB_USERNAME:local}
    password: ${CONF_MODU_TICKET_DB_PASSWORD:local}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:mysql://${CONF_MODU_TICKET_DB_HOST:localhost}:${CONF_MODU_TICKET_DB_PORT:3306}/${CONF_MODU_TICKET_DB_DATABASE:modu_ticket}
    user: ${CONF_MODU_TICKET_DB_USERNAME:local}
    password: ${CONF_MODU_TICKET_DB_PASSWORD:local}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /api/**

jwt:
  header: Authorization
  secret: bW9kdS10aWNrZXQ=
  token-validity-in-seconds: 60

elasticsearch:
  host: ${CONF_MODU_TICKET_ELASTICSEARCH_HOST:localhost}
  port: ${CONF_MODU_TICKET_ELASTICSEARCH_PORT:9300}
  username: ${CONF_MODU_TICKET_ELASTICSEARCH_USERNAME:admin}
  password: ${CONF_MODU_TICKET_ELASTICSEARCH_PASSWORD:admin}
  index:
    concert: ${CONF_MODU_TICKET_ELASTICSEARCH_INDEX_CONCERT:concerts-v1}
