name: SpotlessLint

on:
  pull_request:
    branches: 
    - '**'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Spotless Apply
      run: ./gradlew spotlessApply
    - name: Spotless Check
      run: ./gradlew spotlessCheck